services:
  postgres:
    image: postgres:latest
    container_name: binventory-db
    volumes:
      - binventory-db:/var/lib/postgresql/data
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "echo", "$POSTGRES_DB","&&","pg_is_ready", "-d", "$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - binventory-net

  app:
    build: .
    container_name: binventory-app
    env_file: .env.prod
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    networks:
      - binventory-net
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

networks:
  binventory-net:
    driver: bridge

volumes:
  binventory-db:
